config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :castles do
    resources :reservations, only: [:new , :create]
    resources :reviews, only: [:new, :create]
  end
  resources :reservations, only: [:edit, :update, :delete]
  root to: 'castles#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/castle.rb
class Castle < ApplicationRecord
  belongs_to :user
  has_many :reservation
  has_many :castle

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :castle
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :castle
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :castles
  has_many :reservations
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController

  before_action :set_castle, only: [:show, :edit, :update, :destroy];
  
  def index
    @castles = Castle.geocoded
    @markers = @castles.map do |castle|
      {
        lat: castle.latitude,
        lng: castle.longitude,
      }
    end
  end

  def show
    @castle
  end
  
  def new
    @castle = Castle.new
  end

  def create
    @castle = Castle.new(castle_params)
    @castle.user = current_user
    if @castle.save
      flash[:success] = "Castle successfully created"
      redirect_to @castle
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def edit
    @castle
  end
  
  def update
      if @castle.update_attributes(castle_params)
        flash[:success] = "Castle was successfully updated"
        redirect_to @castle
      else
        flash[:error] = "Something went wrong"
        render 'edit'
      end
  end
  
  def destroy
    if @castle.destroy
      flash[:success] = 'Castle was successfully deleted.'
      redirect_to castles_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to castles_url
    end
  end
  
  private

  def set_castle
    @castle = Castle.find(params[:id])
  end

  def castle_params
    params.require(:castle).permit(:img,:name,:price,:details,:city,:address)
  end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
    def create
        @reservation = reservation.new(reservation_params)
        if @reservation.save
          redirect_to castle_path(@castle)
        else
          render 'new'
        end
    end

    def new
        @reservation = reservation.new
        end
    end

    def edit
        @reservation 
        end 
    end 

    def update
            if @reservation.update_attributes(reservation_params)
                flash[:success] = "reservation was successfully updated"
                redirect_to reservation_url
            else
                flash[:error] = "Something went wrong"
                render 'edit'
            end
        end

    def destroy
        @reservation = reservation.find(params[:id])
        @reservation.destroy
        redirect_to reservation_url
    end

  private

    def reservation_params
        params.require(:reservation).permit(:arrival_date, :departure_date, :reservation, :user)
        end
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
    def create
        @reservation = reservation.new(reservation_params)
        if @reservation.save
          redirect_to castle_path(@castle)
        else
          render 'new'
        end
    end

    def new
        @reservation = Reservation.new
    end

    def edit
        @reservation 
    end 

    def update
            if @reservation.update_attributes(reservation_params)
                flash[:success] = "reservation was successfully updated"
                redirect_to reservation_url
            else
                flash[:error] = "Something went wrong"
                render 'edit'
            end
        end

    def destroy
        @reservation = reservation.find(params[:id])
        @reservation.destroy
        redirect_to reservation_url
    end

  private

    def reservation_params
        params.require(:reservation).permit(:arrival_date, :departure_date, :reservation, :user)
    end
end

app/controllers/review_controller.rb
class ReviewController < ApplicationController
    def create
        @review = review.new(review_params)
        if @review.save
          redirect_to review_path(@review)
        else
          render 'new'
        end
    end

    def new
        @review = review.new
    end

  private

    def review_params
        params.require(:review).permit(:stars, :description, :castle, :user)
        end
    end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
        @review = review.new(review_params)
        if @review.save
          redirect_to review_path(@review)
        else
          render 'new'
        end
    end

    def new
        @review = Reviews.new
    end

  private

    def review_params
        params.require(:review).permit(:stars, :description, :castle, :user)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/castles/index.html.erb
<h1>ALL CASTLES AVAILABLE</h1>
<div class="card-deck">
  <% @castles.each do |castle| %>


  <div class="card" style="width: 18rem;">
    <%= image_tag castle.img, :class => "card-img-top" %>
    <div class="card-body">
      <h5 class="card-title"><%= castle.name %></h5>
      <p class="card-text"><%=castle.address %></p>
      <p class="card-text"><%=castle.city%></p>
      <a href="castles/<%=castle.id%>" class="btn btn-primary">Show Castle</a>
    </div>
  </div>

  <%end%>
</div>

app/views/castles/map_box.html.erb
<h1><%= castle.name%></h1>
<p><%= castle.address%></p>

app/views/castles/new.html.erb
<%= simple_form_for @castle do |f| %>
<%= f.input :name %>
<%= f.input :price %>
<%= f.input :details %>
<%= f.input :city %>
<%= f.input :address %>
<%= f.input :img %>
<%= f.button :submit, class: "btn-primary" %>
<% end %>

app/views/castles/show.html.erb
<div class="container">
  <div class="card mb-3">
    <%= image_tag @castle.img, :class => "card-img-top"%>
    <div class="card-body">
      <h5 class="card-title"><%= @castle.name%></h5>
      <p class="card-text"><%= @castle.details%></p>
      <p class="card-text"><small class="text-muted"><%= @castle.address%></small></p>
      <p class="card-text"><small class="text-muted"><%= @castle.city%></small></p>
    </div>
  </div>
  <a href="<%=@castle.id%>/reservations/new" class="btn btn-primary">Reservation</a>
  <a href="<%=@castle.id%>/reviews/new" class="btn btn-primary">Add Review</a>

<div id="map"
     style="width: 100%; height: 600px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Castlebnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reservations/edit.html.erb
<div class="container">
  <div>
    <h1> TO DO PAGE</h1>
  </div>
  <div>
    <%= link_to 'Back', :back, :class => "btn btn-primary"%>
  </div>
</div>

app/views/reservations/new.html.erb
<div class="container">
  <div>
    <h1> TO DO PAGE</h1>
  </div>
  <div>
    <%= link_to 'Back', :back, :class => "btn btn-primary"%>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <div>
    <h1> TO DO PAGE</h1>
  </div>
  <div>
    <%= link_to 'Back', :back, :class => "btn btn-primary"%>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>
<% if alert %>
<div class="alert alert-warning alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Add Castle", new_castle_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/GuzelGokhan", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</div>